[2023-07-08 10:49:33,101] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.10.167:5000 (Press CTRL+C to quit) - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-07-08 10:49:33,113] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-07-08 10:49:36,014] INFO _log() L224  127.0.0.1 - - [08/Jul/2023 10:49:36] "GET /livros HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-07-08 10:49:37,465] INFO _log() L224  127.0.0.1 - - [08/Jul/2023 10:49:37] "OPTIONS /alteralivro?nome_livro=Harry&ja_lido=Sim HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-07-08 10:49:37,473] ERROR log_exception() L1450 Exception on /alteralivro [PUT] - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\flask\app.py L1450
Traceback (most recent call last):
  File "C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\flask_openapi3\scaffold.py", line 281, in wrapper
    **kwargs
  File "C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "C:\Users\Catarina Sabbadim\Desktop\meu_app_api\meu_app_api\app.py", line 130, in altera_livro
    previsao_leitura = datetime.strptime(query.previsao_leitura, '%d/%m/%Y')
  File "c:\program files\python37\lib\_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "c:\program files\python37\lib\_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%d/%m/%Y'
[2023-07-08 10:49:37,480] INFO _log() L224  127.0.0.1 - - [08/Jul/2023 10:49:37] "[35m[1mPUT /alteralivro?nome_livro=Harry&ja_lido=Sim HTTP/1.1[0m" 500 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-07-08 10:49:39,331] INFO _log() L224  127.0.0.1 - - [08/Jul/2023 10:49:39] "OPTIONS /alteralivro?nome_livro=Harry&quer_ler=Não HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-07-08 10:49:39,337] ERROR log_exception() L1450 Exception on /alteralivro [PUT] - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\flask\app.py L1450
Traceback (most recent call last):
  File "C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\flask_openapi3\scaffold.py", line 281, in wrapper
    **kwargs
  File "C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "C:\Users\Catarina Sabbadim\Desktop\meu_app_api\meu_app_api\app.py", line 130, in altera_livro
    previsao_leitura = datetime.strptime(query.previsao_leitura, '%d/%m/%Y')
  File "c:\program files\python37\lib\_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "c:\program files\python37\lib\_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%d/%m/%Y'
[2023-07-08 10:49:39,343] INFO _log() L224  127.0.0.1 - - [08/Jul/2023 10:49:39] "[35m[1mPUT /alteralivro?nome_livro=Harry&quer_ler=Não HTTP/1.1[0m" 500 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-07-08 10:49:41,728] INFO _log() L224  127.0.0.1 - - [08/Jul/2023 10:49:41] "GET /livros HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-07-08 10:50:09,257] INFO _log() L224   * Detected change in 'C:\\Users\\Catarina Sabbadim\\Desktop\\meu_app_api\\meu_app_api\\schemas\\livro.py', reloading - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-07-08 10:50:09,382] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-07-08 10:50:17,001] INFO _log() L224  127.0.0.1 - - [08/Jul/2023 10:50:17] "GET /livros HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-07-08 10:50:20,427] INFO _log() L224  127.0.0.1 - - [08/Jul/2023 10:50:20] "OPTIONS /alteralivro?nome_livro=Harry&ja_lido=Sim HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-07-08 10:50:20,459] INFO _log() L224  127.0.0.1 - - [08/Jul/2023 10:50:20] "PUT /alteralivro?nome_livro=Harry&ja_lido=Sim HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-07-08 10:50:21,185] INFO _log() L224  127.0.0.1 - - [08/Jul/2023 10:50:21] "OPTIONS /alteralivro?nome_livro=Harry&quer_ler=Não HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-07-08 10:50:21,207] INFO _log() L224  127.0.0.1 - - [08/Jul/2023 10:50:21] "PUT /alteralivro?nome_livro=Harry&quer_ler=Não HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-07-08 10:50:22,588] INFO _log() L224  127.0.0.1 - - [08/Jul/2023 10:50:22] "GET /livros HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-07-08 10:51:55,072] INFO _log() L224  127.0.0.1 - - [08/Jul/2023 10:51:55] "OPTIONS /livro?nome_livro=Harry HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-07-08 10:51:55,099] INFO _log() L224  127.0.0.1 - - [08/Jul/2023 10:51:55] "DELETE /livro?nome_livro=Harry HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-07-08 10:52:05,840] INFO _log() L224  127.0.0.1 - - [08/Jul/2023 10:52:05] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-07-08 10:52:05,881] INFO _log() L224  127.0.0.1 - - [08/Jul/2023 10:52:05] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-07-08 10:52:06,188] INFO _log() L224  127.0.0.1 - - [08/Jul/2023 10:52:06] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-07-08 10:52:06,190] INFO _log() L224  127.0.0.1 - - [08/Jul/2023 10:52:06] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-07-08 10:52:06,518] INFO _log() L224  127.0.0.1 - - [08/Jul/2023 10:52:06] "[36mGET /openapi/static/images/apidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-07-08 10:52:08,393] INFO _log() L224  127.0.0.1 - - [08/Jul/2023 10:52:08] "GET /livros HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
